pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'flask-web-app' 
    }

    stages {
        stage('SCM') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarQube Scanner'
                    withSonarQubeEnv() {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Install Syft and Grype') {
            steps {
                script {
                    // Install Syft and Grype tools
                    echo 'Installing Syft and Grype...'
                    sh '''
                        curl -sSfL https://github.com/anchore/syft/releases/download/v0.48.0/syft-linux-amd64 -o /usr/local/bin/syft
                        chmod +x /usr/local/bin/syft
                        curl -sSfL https://github.com/anchore/grype/releases/download/v0.40.0/grype-linux-amd64 -o /usr/local/bin/grype
                        chmod +x /usr/local/bin/grype
                    '''
                }
            }
        }

        stage('Generate SBOM with Syft') {
            steps {
                script {
                    // Generate SBOM using Syft
                    echo 'Generating SBOM using Syft...'
                    sh "syft docker:${DOCKER_IMAGE} -o json > sbom.json"
                }
            }
        }

        stage('Vulnerability Scan with Grype') {
            steps {
                script {
                    // Run Grype vulnerability scan using SBOM generated by Syft
                    echo 'Running vulnerability scan with Grype...'
                    sh "grype sbom:sbom.json --fail-on high --output json > grype-report.json"
                }
            }
        }

        stage('Vulnerability Scan with Trivy') {
            steps {
                script {
                    // Run Trivy vulnerability scan
                    echo 'Running vulnerability scan with Trivy...'
                    sh 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:0.61.0 image flask_web_app'
                }
            }
        }
    }
}
